name: Build and Release Unity MCP Package

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: unity-mcp-node/package-lock.json
          
      - name: Install dependencies
        working-directory: unity-mcp-node
        run: npm ci
        
      - name: Build project
        working-directory: unity-mcp-node
        run: npm run build
        
      - name: Create Server~ directory
        run: mkdir -p MCPLearning/Assets/Packages/unity-mcp-learning/Server~
        
      - name: Copy build artifacts
        run: |
          cp -r unity-mcp-node/dist MCPLearning/Assets/Packages/unity-mcp-learning/Server~/
          cp -r unity-mcp-node/node_modules MCPLearning/Assets/Packages/unity-mcp-learning/Server~/
          cp -r unity-mcp-node/schema MCPLearning/Assets/Packages/unity-mcp-learning/Server~/
          cp unity-mcp-node/package.json MCPLearning/Assets/Packages/unity-mcp-learning/Server~/
          cp unity-mcp-node/mcp-config.json MCPLearning/Assets/Packages/unity-mcp-learning/Server~/
          cp unity-mcp-node/tsconfig.json MCPLearning/Assets/Packages/unity-mcp-learning/Server~/
          cp unity-mcp-node/tsconfig.build.json MCPLearning/Assets/Packages/unity-mcp-learning/Server~/
          
      - name: Copy UI files
        run: |
          mkdir -p MCPLearning/Assets/Packages/unity-mcp-learning/Server~/Scripts/Editor/Windows
          cp MCPLearning/Assets/Packages/unity-mcp-learning/Scripts/Editor/Windows/MCPServerManagerWindow.uxml MCPLearning/Assets/Packages/unity-mcp-learning/Server~/Scripts/Editor/Windows/
          cp MCPLearning/Assets/Packages/unity-mcp-learning/Scripts/Editor/Windows/MCPServerManagerWindow.uss MCPLearning/Assets/Packages/unity-mcp-learning/Server~/Scripts/Editor/Windows/
          
      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Commit and push changes
        run: |
          git add -f MCPLearning/Assets/Packages/unity-mcp-learning/Server~
          git commit -m "release: Add built Server~ contents for ${{ github.ref_name }}"
          git tag -d ${{ github.ref_name }}
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }} --force